name: Build and lint Kubernetes resources

on:
  push:
    branches-ignore: 
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  build-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dashboards/k8s-build/requirements.txt
      - name: Lint Python scripts with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 dashboards/k8s-build --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 dashboards/k8s-build --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build resources
        run: |
          dashboards/k8s-build/bin/clean.py
          dashboards/k8s-build/bin/build.py
  lint-yaml:
    needs: build-k8s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dashboards/k8s-build/requirements.txt
      - name: Lint generated YAML files
        run: |
          yamllint dashboards/k8s-build/generated
